addSbtPlugin("com.dwijnand"      % "sbt-dynver"           % "3.3.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"         % "2.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"           % "5.1.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"         % "0.9.7-1")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.4.0")
addSbtPlugin("io.spray"          % "sbt-revolver"         % "0.9.1")
